# Generated by Django 5.0.4 on 2024-04-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='EmailID',
            field=models.EmailField(max_length=255),
        ),
    ]
