# Generated by Django 5.0.4 on 2024-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admin_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='EmailID',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
