# Generated by Django 5.0.4 on 2024-04-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_assignment_course_alter_assignment_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentFeedback',
        ),
    ]
