# Generated by Django 5.0.4 on 2024-04-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_assignmentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('c1', 'Tech Courses'), ('c2', 'Grade 9'), ('c3', 'Grade 10'), ('c4', 'Grade 11'), ('c5', 'Grade 12')], default='c1', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=1, verbose_name='Course Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
