# Generated by Django 5.0.4 on 2024-04-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_category_course_course_description_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
    ]
