# Generated by Django 5.0.4 on 2024-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='category_type',
            field=models.CharField(choices=[('c1', 'Tech Courses'), ('c2', 'Grade 9'), ('c3', 'Grade 10'), ('c4', 'Grade 11'), ('c5', 'Grade 12')], default='c1', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
