# Generated by Django 5.0.4 on 2024-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_studentassignment_marked_assignmentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
