# Generated by Django 5.0.4 on 2024-04-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_studentassignment_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='marks',
        ),
    ]
