# Generated by Django 4.1.4 on 2024-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_remove_student_username_student_dob_student_emailid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="user",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="EmailID",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
