# Generated by Django 4.1.4 on 2024-05-03 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_remove_enrollment_user_enrollment_emailid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="EmailID",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
