# Generated by Django 4.1.4 on 2024-05-03 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_alter_enrollment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="DOB",
        ),
        migrations.RemoveField(
            model_name="student",
            name="EmailID",
        ),
        migrations.RemoveField(
            model_name="student",
            name="Full_Name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="Gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="Mobile_no",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
