# Generated by Django 4.1.4 on 2024-05-04 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0037_admin_alter_enrollment_user_alter_mentorship_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
