# Generated by Django 4.1.4 on 2024-05-04 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0038_delete_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admin",
            new_name="Student",
        ),
    ]
