# Generated by Django 4.1.4 on 2024-05-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0042_comment_dislikes_comment_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="staticfiles/videos/")),
            ],
        ),
    ]
