# Generated by Django 4.1.4 on 2024-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0044_remove_course_course_video_course_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="videos",
        ),
        migrations.AddField(
            model_name="course",
            name="course_video",
            field=models.FileField(
                blank=True, null=True, upload_to="staticfiles/course_videos/"
            ),
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
