# Generated by Django 4.1.4 on 2024-05-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0045_remove_course_videos_course_course_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration_in_weeks",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("duration_in_days", models.PositiveIntegerField(default=7)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="staticfiles/topic_videos/"
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.week"
                    ),
                ),
            ],
        ),
    ]
