# Generated by Django 4.1.4 on 2024-05-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0047_coursecontent_remove_week_course_delete_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="weeks",
            field=models.TextField(default="[]"),
        ),
        migrations.DeleteModel(
            name="CourseContent",
        ),
    ]
