# Generated by Django 4.1.4 on 2024-05-10 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0048_course_weeks_delete_coursecontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="duration_in_weeks",
        ),
        migrations.RemoveField(
            model_name="course",
            name="weeks",
        ),
    ]
